### ISSUE TITLE
Use generators in Match

### ISSUE THREAD

**Issue by jccriado** [jccriado/matchingtools#15]
The use of generators may improve the performance of some of the functions of the class `Match`. The reason is that in several places, it is necessary that every possibility _can_ be generated, but often not all of them are needed afterwards. For example, if `Match.all_matches` was a generator, `Operator.__eq__` could terminate early if one of the matches gives the correct pattern of free indices. All the other matches could be discarded.

**Comment by namasme** [comment]
Fixed in 3bfea4d42a7762960bd0c40d09b758a2f086c38a
