### ISSUE TITLE
Use TravisCI

### ISSUE THREAD

**Issue by namasme** [jccriado/matchingtools#21]
It would be nice to integrate the running of the tests and a PEP8 linter/checker (such as flake8) with a CI service like Travis.

**Comment by jccriado** [comment]
This seems to be finished in de4204432a624808d690364575daba4a4d8c57b4

**Comment by namasme** [comment]
Actually a1b0f53006ce53ad0cd643238975637c39029ea2, but yes, I'm closing this.
