### ISSUE TITLE
Improve tests organization

### ISSUE THREAD

**Issue by namasme** [jccriado/matchingtools#4]
This should be priority # 1 after settling on the interface and functionality distribution over the modules.

**Comment by namasme** [comment]
I think we have achieved this more or less but there's the issue of the tests code organization. Global variables are probably not recommended and we should use `setUp` instead.

**Comment by jccriado** [comment]
The problem with using attributes is the verbosity of the code:
```
self.rule.apply(self.sigma(self.I, self.a, self.b) * self.sigma(self.I, self.c, self.d))
```
But I'm not completely against them if there's some concrete advantage of their use (or disadvantage of the global variables).

**Comment by namasme** [comment]
From the [official documentation](https://docs.python.org/3/library/unittest.html#organizing-test-code):

> The testing code of a TestCase instance should be entirely self contained, such that it can be run either in isolation or in arbitrary combination with any number of other test cases.

**Comment by jccriado** [comment]
OK. The change should be easy to do. Some extra formatting will be needed to make the new code clearer.
