### ISSUE TITLE
Choosing convention for the ordering of indices in Differentiable.nth_derivative

### ISSUE THREAD

**Issue by jccriado** [jccriado/matchingtools#7]
The method `Differentiable.nth_derivative` returns the n-th derivative of `self`, where the list of indices of the successive derivatives is given as an argument.

A convention must be chosen for the ordering of this list, either `x.nth_derivative([i1, i2, i3])` is equivalent to:
- `D(i1, D(i2, D(i3, x)))`, or to
- `D(i3, D(i2, D(i1, x)))`.

**Comment by namasme** [comment]
Since, as you pointed out, this mostly comes down to convention I think I'm gonna go with the latter since  it resembles what you would actually get with

`x.differentiate(i1).differentiate(i2).differentiate(i3)`

but the other one would be completely fine with me too.

**Comment by jccriado** [comment]
This is a reasonable criterion to take
