### ISSUE TITLE
Fix Match._map_tensors

### ISSUE THREAD

**Issue by jccriado** [jccriado/matchingtools#9]
The current implementation of `Match._map_tensors` does not work as expected and it is causing the the failure of the tests in test\_permutations\_match.py.

When this issue is fixed, `Match._map_tensors` should produce the full collection of all possible mappings (previous to checking the pattern of index contractions).

**Comment by namasme** [comment]
Looks like this got fixed in 0ea9c0c (?)

**Comment by jccriado** [comment]
Agree
